Question 1: 20  <br />
Question 2: 20  <br />
Question 3: 20  <br />
Question 4: Line 13 returns an error because result is defined using `let` which means that it cannot be accessed outside the block it is defined in. Line 13 is outside the block and hence we get an error.  <br />
Question 5: The code returns an error because result is defined using `const` which means that it cannot be reassigned after it is already assigned for the first time. Since `result = 0` has already been assigned the program cannot compute `result = num1+num2` and the code gives us an error.  <br />
Question 6: The code returns an error because result is defined using `const` which means that it cannot be reassigned after it is already assigned for the first time. Since `result = 0` has already been assigned the program cannot compute `result = num1+num2` and the code gives us an error.  <br />